#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10
#define HIDDEN_WILD_COUNT   3

#define NUM_ALTERING_CAVE_TABLES 9

#define FISHING_CHAIN_LENGTH_MAX 200
#define FISHING_CHAIN_SHINY_STREAK_MAX 20

// Compatibility fallbacks for projects that omit old/super rod chance defines.
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0
#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0 70
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_1
#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_1 (ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0 + 30)
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_TOTAL
#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_TOTAL (ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_1)
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5 40
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5 + 40)
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6 + 15)
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7 + 4)
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_9
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_9 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8 + 1)
#endif
#ifndef ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_TOTAL
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_TOTAL (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_9)
#endif

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
